events {}

http {
  upstream frontend {
    server frontend:3000;
  }

  server {
    listen 80;

    server_name _;

    location /_next/ {
      proxy_pass http://frontend;
      proxy_set_header Host $host;
    }

    location / {
      proxy_pass http://frontend;
      proxy_set_header Host $host;
    }

    # aici poți adăuga ulterior locații spre backend-urile FastAPI
    # location /api/ {
    #   proxy_pass http://backend:8000;
    # }
  }
}
